### ISSUE TITLE
Feature request: Ability to remove Kudos

### ISSUE THREAD

**Issue by davidatada** [mathsian/dashboard#13]
Several times I have submitted the wrong category, just now I accidentally submitted the same Kudos twice. I am unable to read simple confirmation messages and require the ability to undo my easily-avoidable mistakes.

**Comment by mathsian** [comment]
:grin:  This would be a good feature for sure but might be a few weeks away... in the meantime drop me an email with the corrections you want to make and I can make them

**Comment by mathsian** [comment]
... for a sufficiently large value of "a few". This is now implemented. Have a look at the "My Stuff" page. You can edit and delete your kudos and concerns. Let me know how it works for you.
