### ISSUE TITLE
Change name of student to the same of the name he uses and the same as his email

### ISSUE THREAD

**Issue by sierrajulietromeo** [mathsian/dashboard#14]
The Y12 student whose first name starts with Ik  (check your email autocomplete), has a different first name in the system. Can the one in the system be aligned with his email? Spent ages looking for him!

**Comment by mathsian** [comment]
There's a conversation ongoing about legal names, preferred names, emails... I'll email you separately. Long story short, imo we should refer to sts by their preferred name - which isn't always the first part of their email address unfortunately.
