### ISSUE TITLE
Feature request: Choice of emailing the learner if issuing a kudos

### ISSUE THREAD

**Issue by sierrajulietromeo** [mathsian/dashboard#4]
Choice of emailing the learner if issuing a kudos so they are aware.

**Comment by sierrajulietromeo** [comment]
Ian, might this happen once your role is expanded?

**Comment by mathsian** [comment]
Yes 😀🤞

**Comment by sierrajulietromeo** [comment]
Talking to students today and they loved getting kudos. I told some I was giving it.  Even better if that was automatic.  I really do think this feature would enhance the whole Kudos system.    Thanks Ian.

**Comment by davidatada** [comment]
With SV on the case for improving kudos now would be great if we could make this happen...

**Comment by sierrajulietromeo** [comment]
Seems to be an issue with sending emails.  "Email not sent. Problem logged."
