### ISSUE TITLE
No students appearing in list. (Was working last night)

### ISSUE THREAD

**Issue by sierrajulietromeo** [mathsian/dashboard#5]
Have tried two different browsers.     No students in a list when you select a cohort.   Thabo was also able to replicate this issue himself.

![image](https://user-images.githubusercontent.com/30177706/94785213-30617280-03c7-11eb-8bf9-38abbd4b49c2.png)

**Comment by mathsian** [comment]
Thanks Steve. Typo crept in yesterday that didn't come to light till this morning. Should be working now.
