### ISSUE TITLE
Feature request:  Searching for a student

### ISSUE THREAD

**Issue by sierrajulietromeo** [mathsian/dashboard#55]
Where is the code that deals with filtering down to a particular student?  If I type joe  when I'm searching for Joe, it will not find it. I would like the search box to automatically match against a name regardless of the capitalisation of the first letter.

Happy to look myself if you can point me to the file

**Comment by mathsian** [comment]
The student selection table is still a Dash DataTable which is case-sensitive and needs an enter. It will soon be a DashTabulator component - like the pastoral and academic tables - which will work more as you'd like.

**Comment by mathsian** [comment]
This is done now. Let me know if it meets your needs

**Comment by sierrajulietromeo** [comment]
Awesome, works a treat. Thank you.
